modLoader = "kotlinforforge"
loaderVersion = "[4,)"
license = "AGPL-3.0"
issueTrackerURL = "https://github.com/Earu/neo-cs-mc/issues"

[[mods]]
modId = "chatsounds"
version = "${version}"
displayName = "Chatsounds"
logoFile = "assets/chatsounds/icon.png"
description = '''Memes ported into your own Minecraft, free of charge.'''
authors = "Earu"

[[dependencies.chatsounds]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chatsounds]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"
